config/routes.rb
Rails.application.routes.draw do
  

  get '/hospedajes/solCuenta'
  get '/hospedajes/validar'
  
  root 'hospedajes#index'

devise_for :usuarios, :controllers => {:registrations => "usuario/registrations"}

get 'usuario' => 'usuario#new'

  resources :tipos, :hospedajes

end

app/models/hospedaje.rb
class Hospedaje < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :tipo
	has_many :comentarios
	has_many :fotos
	has_many :puntajes
	default_scope -> { order :id }
end

app/controllers/hospedajes_controller.rb
class HospedajesController < ApplicationController 
def index
		 @hospe=Hospedaje.all
end

def solCuenta

end

def show

	@hospe=Hospedaje.find(params[:id])
	@total=-1 
	i=0
    tot=0
    	
    	if @hospe.puntajes.count > 0
			@hospe.puntajes.each do |puntaje|   
				tot= tot + puntaje.puntos
				i = i + 1
				@total= tot / i
			end	#saco el promedio de todos los puntajes
		end	
end
def validar
	if ((params[ :numero ] % 7) < "5")
			redirect_to hospedajes_solCuenta_path, notice: "Numero de tarjeta invalida"
	else 

			idActual=current_usuario.id
			usuarioActual=Usuario.find(idActual)
			usuarioActual.espremium="true"
			usuarioActual.save
			
			redirect_to hospedajes_solCuenta_path, notice: "Usted es ahora usuario premium. Felicitaciones"
	end
end
end

app/views/hospedajes/index.html.erb
<div class="centrado">
	<h2><CENTER>Hospedajes</CENTER></h2>
	<table class="table">
		<tr>
			<th width="100"> Titulo </th>
			<th width="100"> Descripcion </th>
			<th width="100"> Ciudad </th>
			<th width="100"> Tipo de Hospedaje </th>
			<th width="100">  </th>
		</tr>
	</table>

	<% @hospe.each do |hospedaje| %>	
		<table class="table">
			<tr>
				<td width="100"> <%= hospedaje.titulo %> </td>
				<td width="100"> <%= hospedaje.encabezado %> </td>
				<td width="100"> <%= hospedaje.ciudad %> </td>
				<td width="100"> <%= hospedaje.tipo.nombre %> </td>
					
				<% if usuario_signed_in? %> 	
					<td width="100"> <%= link_to "Ver Detalles", hospedaje_path(hospedaje), class: 'btn btn-info btn-xs' %> </td>
				<% else %>
					<td width="100"></td>
				<% end %>	
			</tr>
		</table>
		<% if  hospedaje.usuario.espremium %>
			<img class="slideIndex" src=<%= hospedaje.fotos.first.link %> />
		<% else %>		
		 	<img class="slideInd" src="https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xtf1/v/t1.0-9/12208452_1015580821795433_8228123211197963475_n.jpg?oh=41ef7b224ff9685835bfc56f8442aa38&oe=56F623FA&__gda__=1455207506_469b355130ec06d56979dcc23c2790df"  />
		 	<br/> 
		<% end %>	
	<% end %>	
	
</div>

app/views/hospedajes/show.html.erb
<div class="centrado">
	<hr/>
	<h1><CENTER> <%= @hospe.titulo %> </CENTER></h1>

	<hr/>
   
 	<h4> Dueño:  </h4>
 	<h5>  <%= @hospe.usuario.nombre + " " + @hospe.usuario.apellido %> </h5> 

 	<h4> Capacidad:  </h4>
 	<h5>  <%= @hospe.capacidad %> personas</h5>

 	<h4> Provincia:  </h4>
 	<h5>  <%= @hospe.provincia %> </h5>

 	<h4> Ciudad:  </h4>
 	<h5>  <%= @hospe.ciudad %> </h5>

 	<h4>  Caracteristicas:  </h4> 
    <h5> <%= @hospe.descripcion %> </h5>

 	<h4> Valoracion del Hospedaje:  </h4>
 	<% if @total != -1 %>
 		<h5>  <%= @total %> puntos de 10    <%= link_to "Ver Puntajes", nil, class: 'btn btn-info btn-xs' %> </h5>
 	<% else %>
		<h5>  Este hospedaje no posee puntajes </h5> 	
 	<% end %>	

 	<hr/>

    <meta charset="UTF-8">
		<script src="functions.js"></script>
		<div class="slide">
    	 	<figure>
    	 		<% j = 0 %>
         		<% @hospe.fotos.each do |foto| %>   
          			<% i = 1 + j %>   <!-- controla que el each no se pasa del tamaño del arreglo-->
          			<% if i <= 4 %>
          				 <!-- VERIFICAR POR QUE TARDA -->
          				<% while i <= 4 %>
          					<img class="img<%=i%>" alt="alt img<%=i%>" src=<%= foto.link %> />
          					<% i = i + @hospe.fotos.count %>
          				<% end %>
          				<% j = j + 1 %>
					<% end %>
				<% end %>
			</figure>
     	</div>
	
	
     <hr/>

	<!-- COMIENZA LA PARTE DE COMENTARIOS-->

	<h3>  Comentarios:  </h3>
	 	<% if @hospe.comentarios.count > 0 %>
		 	<% @hospe.comentarios.each do |comentario| %>
				<h5> <strong> <%= comentario.usuario.nombre %> </strong>  :  <%= comentario.texto  %>
					<%= link_to "Responder", nil, class: 'btn btn-info btn-xs' %> </h5>
				 <% comentario.respuestas.each do |respuesta| %> 
					<div class="respuesta"> <h5> <strong> <%= respuesta.usuario.nomusuario %> </strong>  : <%= respuesta.texto  %> </h5> </div>  
		 		<% end %>
		 		<hr/>
		 	<% end %>
		
		<% else %>
			<h5>  Este hospedaje no posee comentarios </h5>
		<% end %>
	<br/>
	<CENTER> <%= link_to "Solicitar Hospedaje", nil, class: 'btn btn-success btn-lg' %>
	<%= link_to "Volver", hospedajes_path, class: 'btn btn-warning btn-lg' %> </CENTER>
	<br/>
</div>

app/views/hospedajes/solCuenta.html.erb
<div class="centrado">

<h2><CENTER>Solicitud de cuenta Premium</CENTER></h2>

 	<div class="col-md-6 col-md-offset-3">

 	<h3><CENTER>Elija su tarjeta de credito</CENTER></h3>
	
	<%= form_tag '/hospedajes/validar', :method => "get" do  %>

	<h5> <%= radio_button_tag :tarjeta, 'Aerican Express' , checked: true %> American Express </h5>
	<h5> <%= radio_button_tag :tarjeta, 'Cabal' %> Cabal </h5>
	<h5> <%= radio_button_tag :tarjeta, 'Italcred' %> Italcred </h5>
	<h5> <%= radio_button_tag :tarjeta, 'Master card' %> Master Card </h5>
	<h5> <%= radio_button_tag :tarjeta, 'Tarjeta Naranja' %> Tarjeta Naranja </h5>
	<h5> <%= radio_button_tag :tarjeta, 'Visa'  %> Visa </h5>

	<br />
	<CENTER><%= number_field_tag :numero ,nil, :placeholder => 'Ingrese el numero de su tarjeta', required: true ,class:"form-control"%><br /></CENTER>

	<br />
	<CENTER> <%= submit_tag "Realizar Pago", class: "btn btn-success btn-lg" %>
  			 <%= link_to "Volver", hospedajes_path, class: 'btn btn-warning btn-lg' %></CENTER>
	
  	<br/>
  	<% if notice && notice== "Numero de tarjeta invalida" %>
  			 	<div class="alert alert-warning"> <p><%= notice %> </p> </div>
  			 <% elsif notice %>
  			    <div class="alert alert-success"> <p><%= notice %> </p> </div>
  		<% end %>	
	<% end %>

	</div>
 </div>
 