config/routes.rb
Rails.application.routes.draw do
  

  get '/hospedajes/solCuenta'
  get '/hospedajes/validar'
  
  root 'hospedajes#index'

devise_for :usuarios, :controllers => {:registrations => "usuario/registrations"}

get 'usuario' => 'usuario#new'

  resources :tipos, :hospedajes

end

app/views/layouts/_footer.html.erb
<div class="  navbar-fixed-top" role="navigation">
<div class="footer">
<%= link_to "Ayuda",nil %>
<%= link_to "Contacto",nil %>
</div>
</div>

app/views/layouts/_header.html.erb
<header>
    <div class="container">
		<%= image_tag "couchinn.png", title: "Logo", class: "logo" %>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CouchInn</title>
 <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/footer' %>

<div class="menuSesion navbar-fixed-top" role="navigation" > 
	<% if usuario_signed_in? %>
	<strong><big><%= current_usuario.nomusuario %> <big></strong> 
 	<!--<%= link_to 'Editar Perfil', edit_usuario_registration_path, :class => 'navbar-link' %> | -->
 	<%= link_to "Cerrar sesion",destroy_usuario_session_path, method: :delete, :class => 'navbar-link', class: 'btn btn-primary btn-xs'  %>
<% else %>
	<%= link_to "Registrarse", new_usuario_registration_path, :class => 'navbar-link', class: 'btn btn-primary btn-xs'  %> 
  	<%= link_to "Iniciar Sesion", new_usuario_session_path, :class => 'navbar-link', class: 'btn btn-primary btn-xs'  %>
<% end %> 
</div>


<div class="container"> 
<%= yield %>
</div>

</body>
</html>